branches:
  only:
  - reorganize
language: python
env:
  global:
  - AWS_DEFAULT_REGION="us-east-1"
python:
- 3.7
install:
- pip install -r requirements.txt
- pip install ./src
script:
- pytest tests/test_local.py

